services:
  react-flow-roadmap:
    image: rasulovarsen/react-flow-roadmap:latest
    container_name: react-flow-roadmap
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
    restart: unless-stopped
    networks:
      - proftwist-network

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=*/1 * * * *
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_ONLY_INCLUDE=react-flow-roadmap
    restart: unless-stopped
