services:
  react-flow-roadmap:
    image: rasulovarsen/react-flow-roadmap:latest
    build: .
    container_name: react-flow-roadmap
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/live:ro
    restart: unless-stopped
    networks:
      - proftwist-network

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=*/1 * * * *
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_ONLY_INCLUDE=react-flow-roadmap
    restart: unless-stopped

networks:
  proftwist-network:
    external: true
